name: $(BuildDefinitionName)_$(Year:yyyy).$(Month).$(DayOfMonth)$(Rev:.r)
trigger:
  branches:
    include:
    - main
    - Feature*/*
  
pool:
  vmImage: 'ubuntu-latest'
variables:
- group: User credentials

steps:
- pwsh: echo $(Build.BuildNumber) and $[ variablegroups.User Credentials.username ] //output updated build number
