name: Build-Pipeline-MentalHealth
trigger:
  branches:
    include:
    - main
    - Feature*/*
  
pool:
  vmImage: 'ubuntu-latest'
variables:
- group: User credentials

stages:
- stage: Makesurethathepipelineisworking
  dependsOn: []
  displayName: Printinconsolethecontentofthefile1
  jobs:
  - job: Printinconsolethecontentofthefile1
    displayName: "Printinconsolethecontentofthefile1"
    -steps:   
    - task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: 'echo ''Hello ${username}'''
